### ISSUE TITLE
Refactor main.go

### ISSUE THREAD

**Issue by g4s8** [g4s8/gitstrap#5]
Right now all code is located in `main.go`, let's refactor it.

**Comment by g4s8** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/g4s8/gitstrap/issues/5#issuecomment-451914504))

@g4s8 The job [#5](https://github.com/g4s8/gitstrap/issues/5) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CF7JL4282/333a9781-e351-4421-8fe7-52bda33d96f9); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/g4s8/gitstrap/issues/5#issuecomment-451914504))

@g4s8 Job `gh:g4s8/gitstrap#5` already assigned to @g4s8, can't assign to @g4s8

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by g4s8** [comment]
done

**Comment by 0crat** [comment]
Job was finished in 2 hours, bonus for fast delivery is possible (see [§36](http://www.zerocracy.com/policy.html#36))

**Comment by 0crat** [comment]
The job [#5](https://github.com/g4s8/gitstrap/issues/5) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +35 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#25](https://github.com/g4s8/gitstrap/issues/25) is still not solved; solved: [#9](https://github.com/g4s8/gitstrap/issues/9).

**Comment by 0pdd** [comment]
@g4s8 all 2 puzzles are solved here: [#25](https://github.com/g4s8/gitstrap/issues/25), [#9](https://github.com/g4s8/gitstrap/issues/9).
